#!/usr/bin/env bash

# Source global definitions

if [ -f /etc/bashrc ]; then
	# shellcheck source=/dev/null
	source /etc/bashrc
fi

# The script will go no further if you
# are running in a headless (i.e.
# non-interactive) session.
case $- in
*i*) ;;
*) return ;;
esac

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
	for rc in ~/.bashrc.d/*; do
		if [ -f "$rc" ]; then
			# shellcheck source=/dev/null
			. "$rc"
		fi
	done
fi

unset rc

# Enter `fish` shell if it is installed.
if command -v fish &>/dev/null; then
	if [[ $(ps --no-header --pid=$PPID --format=comm) != "fish" && -z ${BASH_EXECUTION_STRING} ]]; then
		echo "Entering fish!"
		shopt -q login_shell && LOGIN_OPTION='--login' || LOGIN_OPTION=''
		exec fish "$LOGIN_OPTION"
	fi
fi
