#!/usr/bin/env bash

find . -type f \
    \( \
        -name "*.bash" \
        -o \
        -name "*.sh" \
        -o \
        -name "*.dash" \
        -o \
        -name "*.ksh" \
        -o \
        -name "executable*" \
    \) \
    -exec sh -c '
        for file; do
            if file --mime-type "$file" | grep -q "text/x-shellscript" && \
               head -n 1 "$file" | grep -qE "^#!.*\b(sh|bash|dash|ksh)\b"; then
                printf "%s\0" "$file"
            fi
        done
    ' sh {} + \
    | xargs -0 shellcheck
