[".local/bin/atuin"]
  type = "archive-file"
  url = "https://github.com/atuinsh/atuin/releases/download/v18.3.0/atuin-x86_64-unknown-linux-gnu.tar.gz"
  path = "atuin-x86_64-unknown-linux-gnu/atuin"

  # This is the checksum of the downloaded `.tar.gz` container
  [".local/bin/atuin".checksum]
    sha256 = "e3716dfb8a68dbf8992c11dbb6cb9be746cf69a32b80075553c94614c7311792"
