[".local/bin/atuin"]
  type = "archive-file"
  url = "https://github.com/atuinsh/atuin/releases/download/v18.2.0/atuin-v18.2.0-x86_64-unknown-linux-gnu.tar.gz"
  path = "atuin-v18.2.0-x86_64-unknown-linux-gnu/atuin"

  [".local/bin/atuin".checksum]
    sha256 = "51ce72545c626a97149e6d141ca53e3f378895568ad39a99e5adace8b95fb6e5"
