[".local/bin/ghq"]
  type = "archive-file"
  url = "https://github.com/x-motemen/ghq/releases/download/v1.6.2/ghq_linux_amd64.zip"
  path = "ghq_linux_amd64/ghq"

  # This is the checksum of the downloaded `.zip` container
  [".local/bin/ghq".checksum]
    sha256 = "b4883f3b4e4771e95bcb34c3e262d48bf2a76a1148aa46edd273bf347c924a4c"
