[".local/bin/ghq"]
  type = "archive-file"
  url = "https://github.com/x-motemen/ghq/releases/download/v1.6.1/ghq_linux_amd64.zip"
  path = "ghq_linux_amd64/ghq"

  [".local/bin/ghq".checksum]
    sha256 = "fa121c76c14608175c52fc0ea53a584f20dda96bcec66909b5f7ee8b75715163"
