name: Shellcheck

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ShellCheck
        run: sudo apt-get install -y shellcheck

      - name: Find and run ShellCheck on all scripts
        run: |
          # Find all .fish, .bash, and .sh files and run shellcheck on them
          find . -type f \( -name "*.fish" -o -name "*.bash" -o -name "*.sh" \) -print0 | xargs -0 shellcheck
